import { getBackendSrv } from '@grafana/runtime';
import type { Template, TemplateMetadata, TemplateVariables, GrafanaDashboard } from '../types';

const PLUGIN_ID = 'gregoor-private-marketplace-app';
const BASE_URL = `/api/plugins/${PLUGIN_ID}/resources`;

// ─── List all templates ───────────────────────────────────────────────────────

export async function listTemplates(): Promise<Template[]> {
  return getBackendSrv().get<Template[]>(`${BASE_URL}/templates`);
}

// ─── Get single template metadata ────────────────────────────────────────────

export async function getTemplateMetadata(id: string): Promise<TemplateMetadata> {
  return getBackendSrv().get<TemplateMetadata>(`${BASE_URL}/templates/${id}`);
}

// ─── Get template dashboard JSON ─────────────────────────────────────────────

export async function getTemplateJson(id: string): Promise<GrafanaDashboard> {
  return getBackendSrv().get<GrafanaDashboard>(`${BASE_URL}/templates/${id}/template`);
}

// ─── Get template variables definition ───────────────────────────────────────

export async function getTemplateVariables(id: string): Promise<TemplateVariables> {
  return getBackendSrv().get<TemplateVariables>(`${BASE_URL}/templates/${id}/variables`);
}

// ─── Get image URL (direct URL, not fetched) ─────────────────────────────────

export function getTemplateImageUrl(id: string): string {
  return `${BASE_URL}/templates/${id}/image`;
}

// ─── Upload a new template (multipart/form-data) ─────────────────────────────

export interface UploadTemplatePayload {
  templateJson: string;     // JSON string
  metadata: string;         // JSON string of TemplateMetadata (without id – generated by backend)
  variablesJson: string;    // JSON string of TemplateVariables
  image?: File;
}

export async function uploadTemplate(payload: UploadTemplatePayload): Promise<TemplateMetadata> {
  const formData = new FormData();
  formData.append('templateJson', payload.templateJson);
  formData.append('metadata', payload.metadata);
  formData.append('variablesJson', payload.variablesJson);
  if (payload.image) {
    formData.append('image', payload.image);
  }

  const response = await fetch(`${BASE_URL}/templates`, {
    method: 'POST',
    body: formData,
    credentials: 'include',
    // Do not set Content-Type – browser sets it with boundary automatically for FormData
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Upload failed: ${response.status} ${errorText}`);
  }

  return response.json() as Promise<TemplateMetadata>;
}

// ─── Delete a template ────────────────────────────────────────────────────────

export async function deleteTemplate(id: string): Promise<void> {
  await getBackendSrv().delete(`${BASE_URL}/templates/${id}`);
}
